name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ğŸ› ï¸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: ğŸ—„ï¸ Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}-py3.8
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: ğŸ“¦ Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: ğŸ› ï¸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
          check-latest: true

      - name: ğŸ—„ï¸ Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-ruff-py3.8
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: ğŸ“¦ Install Ruff
        run: pip install ruff

      - name: ğŸ’… Check formatting
        run: ruff format --check .

      - name: ğŸ” Run linter
        run: ruff check .
